cmake_minimum_required(VERSION 3.16)
project(wall_follow_robot)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_python_install_package(wall_follow_sim)
find_package(rclcpp REQUIRED)
find_package(rcl_interfaces REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
add_executable(controller src/controller.cpp)
target_compile_features(controller PRIVATE cxx_std_17)
target_compile_options(controller PRIVATE -Wall -Wextra -Wpedantic)
target_include_directories(controller PRIVATE include)
ament_target_dependencies(controller rclcpp rcl_interfaces geometry_msgs sensor_msgs)
install(TARGETS controller DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
ament_export_include_directories(include)
ament_package()
