cmake_minimum_required(VERSION 3.16)
project(wall_follow_benchmark)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_python_install_package(wall_follow_host)
ament_python_install_package(wall_follow_benchmark PACKAGE_DIR ../../benchmarking/wall_follow_benchmark)
install(PROGRAMS scripts/collector DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
ament_package()
